### ISSUE TITLE
v1 compatibility with random_compat v1

### ISSUE THREAD

**Issue by rkuntoro** [tuupola/ksuid#9]
A library we're using requires `paragonie/random_compat` v1, so it conflicts with ksuid v1, which requires v2.

I've tested running ksuid v1 with random_compat v1 and it seems to work. Do you forsee any compatibility problems using ksuid v1 with random_compat v1?

**Comment by tuupola** [comment]
There should not be compatibility problems. However 1.x versions of `paragonie/random_compat` have a security advisory because of insecure CSPRNG.

https://github.com/FriendsOfPHP/security-advisories/pull/146
https://github.com/paragonie/random_compat/issues/96

However it should be ok to allow 1.x branch of this library to install the older version of `paragonie/random_compat`. I will sleep over this (it is midnight here) and probably do the change tomorrow.

Thanks for notifying!

**Comment by rkuntoro** [comment]
Thanks, @tuupola

**Comment by tuupola** [comment]
Relased as [1.0.2](https://packagist.org/packages/tuupola/ksuid#1.0.2).
